# Generated by Django 3.2 on 2022-10-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='hacienda',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hacienda',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='hacienda',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='hacienda',
            name='apellido',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido'),
        ),
    ]
