# Generated by Django 3.2 on 2022-10-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnt', '0002_auto_20221021_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='Cultivo',
            new_name='cultivo',
        ),
        migrations.RenameField(
            model_name='asignacion',
            old_name='Actividad',
            new_name='actividad',
        ),
        migrations.RenameField(
            model_name='asignacion',
            old_name='Cultivo',
            new_name='cultivo',
        ),
        migrations.RenameField(
            model_name='asignacion',
            old_name='Empleado',
            new_name='empleado',
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('cultivo', 'nombre', 'fecha')},
        ),
    ]
