# Generated by Django 3.2 on 2022-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idactividad', models.AutoField(primary_key=True, serialize=False)),
                ('idcultivo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idasignacion', models.AutoField(primary_key=True, serialize=False)),
                ('idactividad', models.IntegerField()),
                ('idempleado', models.IntegerField()),
                ('idcultivo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'asignacion',
            },
        ),
        migrations.CreateModel(
            name='AsignacionMaterial',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idmaterial', models.AutoField(primary_key=True, serialize=False)),
                ('idinsumo', models.IntegerField()),
                ('idcultivo', models.IntegerField()),
                ('encargado', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'AsignacionMateriales',
                'db_table': 'asignacion_material',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('cedula', models.CharField(max_length=15)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.CharField(blank=True, max_length=25, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idcosecha', models.AutoField(primary_key=True, serialize=False)),
                ('idhacienda', models.IntegerField()),
                ('idcultivo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Cosechas',
                'db_table': 'cosecha',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idcultivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Cultivos',
                'db_table': 'cultivo',
            },
        ),
        migrations.CreateModel(
            name='DatoEmpleado',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idregistro', models.AutoField(primary_key=True, serialize=False)),
                ('idhacienda', models.IntegerField()),
                ('idempleado', models.IntegerField()),
                ('contrato', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'DatosEmpleados',
                'db_table': 'dato_empleado',
            },
        ),
        migrations.CreateModel(
            name='DescripcionLote',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('iddescripcion_lote', models.AutoField(primary_key=True, serialize=False)),
                ('idcultivo', models.IntegerField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('idproduccion', models.IntegerField()),
                ('etapa', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'DescripcionLotes',
                'db_table': 'descripcion_lote',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('iddetalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('idventa', models.IntegerField()),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('idcliente', models.IntegerField()),
                ('cantidadventa', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'DetalleVentas',
                'db_table': 'detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idempleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('cedula', models.CharField(max_length=15)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.CharField(blank=True, max_length=25, null=True)),
                ('fchnacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Hacienda',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idhacienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc', models.CharField(max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=20, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Haciendas',
                'db_table': 'hacienda',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idinsumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('uso', models.CharField(max_length=50)),
                ('precio', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Insumos',
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idproduccion', models.AutoField(primary_key=True, serialize=False)),
                ('idcultivo', models.IntegerField()),
                ('idinsumo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('cantcosecha', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Producciones',
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='RegistroInusmo',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idregistro_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('fechacompra', models.DateField()),
                ('precio', models.TextField()),
                ('fechaingreso', models.DateField()),
                ('fechaexpira', models.DateField()),
                ('requerimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('idinsumo', models.IntegerField()),
                ('idcultivo', models.IntegerField()),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'RegistroInsumos',
                'db_table': 'registro_inusmo',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fechaModificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('idcultivo', models.IntegerField()),
                ('idproduccion', models.IntegerField()),
                ('cantidad', models.FloatField()),
                ('precio', models.TextField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
    ]
