# Generated by Django 3.2 on 2022-10-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='AsignacionMaterial',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cosecha',
        ),
        migrations.DeleteModel(
            name='Cultivo',
        ),
        migrations.DeleteModel(
            name='DatoEmpleado',
        ),
        migrations.DeleteModel(
            name='DescripcionLote',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Hacienda',
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='Produccion',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='RegistroInusmo',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
